source/mediadores/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from mediadores import settings
from mediadores.emailusernames.forms import EmailAuthenticationForm
from mediadores.text_plain import TextPlainView

# Uncomment the next two lines to enable the admin:
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mediadores.views.home', name='home'),
    # url(r'^mediadores/', include('mediadores.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^robots\.txt$', TextPlainView.as_view(template_name='robots.txt')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','main.views.home' ),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        {'authentication_form': EmailAuthenticationForm}, name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout'),
    url(r'^list/(?P<institutionId>\w+)/$', 'main.views.mediators_list'),
    url(r'^request/(?P<institutionId>\w+)/(?P<mediatorNif>\w+)/$', 'main.views.do_request'),
    url(r'^contact/(?P<institutionId>\w+)/$', 'main.views.contact'),
    url(r'^contact/$', 'main.views.selectAndContact'),
    url(r'^info/(?P<institutionId>\w+)/$', 'main.views.info'),
    url(r'^edit/(?P<mediatorId>\w+)/$', 'main.views.editMediator'),
    url(r'^delete/(?P<mediatorId>\w+)/$', 'main.views.deleteMediator'),
    url(r'^add/$', 'main.views.addMediator'),
    url(r'^insurance-entities/$', 'main.views.insuranceEntities'),
    url(r'^areas/$', 'main.views.areas'),
    url(r'^degrees/$', 'main.views.degrees'),
    url(r'^legal/$', 'main.views.legal'),
    url(r'^reset-password/$', 'main.views.resetPassword'),
    url(r'^userconfig/$', 'main.views.userconfig'),
    url(r'^ajax/add-expertise-area/$','main.views.addExpertiseArea'),
    url(r'^ajax/add-degree/$','main.views.addDegree'),
    url(r'^ajax/get-nif-list/$','main.views.getNifList'),
    url(r'^ajax/get-mediator/$','main.views.getMediator'),
    url(r'^(?P<institutionId>\w+)/$', 'main.views.home_general_institution'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^static-files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_DOC_ROOT}),
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

source/mediadores/main/models.py
# -*- coding: utf-8 -*-
from PIL import Image
from datetime import date
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.db import models
from django.template.context import Context
from django.template.loader import get_template
from mediadores.emailusernames.utils import create_user
from mediadores.main.enums import PROVINCES_SET, INSTITUTION_TYPES, \
    MEDIATION_MODE, PROVINCES_MAP
from mediadores.settings import MEDIA_ROOT, SITE_URL_ROOT
from os import remove
from os.path import join, exists
import random
import string

class Institution(models.Model):
    name=models.CharField(verbose_name=u"denominación", max_length=128, blank=False)
    address=models.CharField(verbose_name=u"dirección", max_length=128, blank=False)
    postalcode=models.CharField(verbose_name=u"código postal", max_length=5, blank=False)
    city=models.CharField(verbose_name=u"población", max_length=64, blank=False)
    website=models.URLField(verbose_name=u"sitio web", null=True, blank=True)
    phone=models.CharField(verbose_name=u"teléfono", max_length=16, default="-")
    fax=models.CharField(verbose_name=u"fax", max_length=16, null=True, blank=True)
    logo=models.ImageField(verbose_name=u"logotipo", upload_to="images", null=True, blank=True)
    institutionType=models.CharField(verbose_name=u"tipo de institución", max_length=2, blank=False, choices=INSTITUTION_TYPES)
    province=models.CharField(verbose_name=u"provincia", max_length=2, blank=False, choices=PROVINCES_SET)
    contactEMail=models.EmailField(verbose_name=u"e-mail de contacto", blank=False)
    mapIframe=models.TextField(verbose_name=u"código del mapa", null=True, blank=True, help_text=u"Código HTML que genera Google Maps para añadir un mapa en un sitio web.")
    mapX=models.IntegerField(verbose_name=u"coodernada X", default=0, help_text=u"Coodenada para de la imagen del mapa de selección inicial")
    mapY=models.IntegerField(verbose_name=u"coodernada Y", default=0, help_text=u"Coodenada para de la imagen del mapa de selección inicial")
    
    def __unicode__(self):
        return self.name
    
class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, blank=True)
    name=models.CharField(verbose_name=u"nombre", max_length=64, blank=False)
    surname=models.CharField(verbose_name=u"apellidos", max_length=128, blank=True)
    email=models.EmailField(verbose_name=u"e-Mail", max_length=75, unique=True)

    def __init__(self, *args, **kwargs):
        super(UserProfile, self).__init__(*args, **kwargs)
        self.mustSendCreationEMail = False

    def __unicode__(self):
        return unicode.format(u"{0} {1}", self.name, self.surname)
    
    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        
        if not self.id or self.id == 0:
            #Crear password aleatorio
            self.passwd = self.createPassword()
            user = create_user(self.email, self.passwd)
            self.user = user
            self.mustSendCreationEMail = True           
        else: #ya existe el usuario
            user = self.user
            user.email = self.email
            user.save()      
        super(UserProfile, self).save(*args, **kwargs)
        
        if self.mustSendCreationEMail:
            # enviar correo al usuario con su password
            self.sendCreationEMail(self.passwd)
        
    def delete(self, *args, **kwargs):
        user = self.user
        super(UserProfile, self).delete(*args, **kwargs)
        user.delete()
    
    def createPassword(self):
        return ''.join(random.choice(string.ascii_lowercase + string.digits) for x in range(8))
    
    def resetPassword(self):
        self.passwd = self.createPassword()
        self.user.set_password(self.passwd)
        self.sendPasswordResetEMail(self.passwd)
    
    def sendCreationEMail(self, passwd):
        raise Exception(u"No se puede enviar correo desde la clase base.")
    
    def sendPasswordResetEMail(self, passwd):
        raise Exception(u"No se puede enviar correo desde la clase base.")
    
    def getClassName(self):
        className = ""
        try:
            self.mediator
            className = Mediator.__name__
        except:
            pass
        try:
            self.institutionadmin
            className = InstitutionAdmin.__name__
        except:
            pass
            
        return className

class ExpertiseArea(models.Model):
    name=models.CharField(verbose_name="campo de experiencia", max_length=64, blank=False)
    
    def __unicode__(self):
        return self.name 

class Degree(models.Model):
        
    name=models.CharField(verbose_name=u"denominación", max_length=64, blank=False, unique=True)
    
    def __unicode__(self):
        return self.name

class InsuranceEntity(models.Model):
        
    name=models.CharField(verbose_name=u"entidad aseguradora", max_length=64, blank=False)
    eMail=models.EmailField(verbose_name=u"e-mail", blank=False)
    phone=models.CharField(verbose_name=u"teléfono", max_length=32, blank=True, null= True)
    address=models.CharField(verbose_name=u"dirección postal", max_length=128, blank=True, null=True)
    city=models.CharField(verbose_name=u"población", max_length=64, blank=True, null=True)
    postalCode=models.CharField(verbose_name=u"código postal", max_length=5, blank=True, null=True)
    province=models.CharField(verbose_name=u"provincia", max_length=2, blank=False, choices=PROVINCES_SET)

    def __unicode__(self):
        return self.name
    
    def provinceName(self):
        return PROVINCES_MAP[self.province]
        
class Mediator(UserProfile):
    nif=models.CharField(verbose_name=u"NIF", max_length=32, help_text=u"DNI o NIF", unique=True)
    institution = models.ManyToManyField(Institution, verbose_name=u"institución")
    address=models.CharField(verbose_name=u"dirección", max_length=128, blank=False)
    postalCode=models.CharField(verbose_name=u"código postal", max_length=5, blank=False)
    city=models.CharField(verbose_name=u"población", max_length=64, blank=False)
    province=models.CharField(verbose_name=u"provincia", max_length=2, blank=False, choices=PROVINCES_SET)
    phoneNumber=models.CharField(verbose_name=u"teléfono", max_length=16, blank=True, null=True)
    mobileNumber=models.CharField(verbose_name=u"tel. móvil", max_length=16, blank=True, null=True)
    faxNumber=models.CharField(verbose_name=u"fax", max_length=16, blank=True, null=True)    
    image=models.ImageField(verbose_name=u"imagen de perfil", upload_to="images/", null=True, blank=True)
    website=models.URLField(verbose_name=u"sitio web", null=True, blank=True)    
    degree=models.ManyToManyField(Degree, verbose_name=u"titulación")
    expertiseArea=models.ManyToManyField(ExpertiseArea, verbose_name=u"área de experiencia")
    description=models.TextField(verbose_name=u"resumen profesional", max_length=4096, help_text=u"Resumen de la experiencia profesional del mediador")    
    expertiseDescription=models.CharField(verbose_name=u"etiquetas", max_length=128, help_text=u"Palabras que definen el ámbito del mediador, separadas por espacios. Por ejemplo: \"tasador propiedad rural\"", blank=True, null=True)
    insuranceEntity=models.ForeignKey(InsuranceEntity, verbose_name=u"entidad aseguradora", blank=True, null=True)
    insuranceContract=models.CharField(verbose_name=u"número de póliza", max_length=32, blank=True, null=True)
    insuranceExpiration=models.DateField(verbose_name=u"expiración de la póliza", blank=True, null=True)
    isCompany=models.BooleanField(verbose_name=u"¿Es una sociedad?", default=False)

    def __unicode__(self):
        return unicode.format(u"{0}: {1} {2}", self.nif, self.name, self.surname)
    
    def provinceName(self):
        return PROVINCES_MAP[self.province]
    
    def hasInsurance(self):
        return self.insuranceEntity and self.insuranceContract and self.insuranceExpiration
    
    def isInsuranceExpired(self):
        return not self.insuranceExpiration or self.insuranceExpiration < date.today()
    
    def save(self, *args, **kwargs):
        imageFileName = join(self.image.field.upload_to, self.nif + ".jpg")
        imageFilePath = join(MEDIA_ROOT, imageFileName)
            
        super(Mediator, self).save(*args, **kwargs)
            
        if self.image.name:
            image = Image.open(self.image.path)
        
            image.thumbnail((100,75), Image.ANTIALIAS)
            image.save(imageFilePath, "JPEG")
            if self.image.name != imageFileName:
                remove(self.image.path)
            
            self.image = imageFileName
            super(Mediator, self).save(*args, **kwargs)
        else:
            if exists(imageFilePath):
                remove(imageFilePath)

    def delete(self, *args, **kwargs):
        super(Mediator,self).delete(*args, **kwargs)
        if self.image.name:
            remove(self.image.path)
    
    def getInstitutionSender(self):
        institutions = self.institution.all()
        if len(institutions) > 0:
            institution = institutions[0]
        else:
            institution = None
            
        return institution
        
    def sendCreationEMail(self, passwd):
        institution = self.getInstitutionSender()
        if institution:
            message = get_template("main/mediator-creation-notify.txt").render(Context({
                                       "mediator": self,
                                       "institution": institution,
                                       "passwd": passwd,
                                       "siteUrl" : SITE_URL_ROOT}))
             
            send_mail(u"Creación de usuario",
                      message,
                      institution.contactEMail,
                      [self.user.email])
            self.mustSendCreationEMail = False
            
    def sendPasswordResetEMail(self, passwd):

source/mediadores/templates/main/admin_nav_buttons.html
<div id="adminNav">
	<button class="adminNavButton" id="mediatorsButton" onclick="javascript:window.location.href='/';">Mediadores</button>
	<button class="adminNavButton" id="insuranceEntitiesButton" onclick="javascript:window.location.href='/insurance-entities';">Aseguradoras</button>
	<button class="adminNavButton" id="expertiseAreasButton" onclick="javascript:window.location.href='/areas';">&Aacute;reas de Experiencia</button>
	<button class="adminNavButton" id="degreesButton" onclick="javascript:window.location.href='/degrees';">Titulaciones</button>
</div>

source/mediadores/templates/main/areas.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
	{% include "jqueryui-headers.html" %}
	<link rel="stylesheet" href="/static-files/css/forms.css" />
	<link rel="stylesheet" href="/static-files/css/admin_nav_buttons.css" />
	<link rel="stylesheet" href="/static-files/css/areas.css" />
	<script type="text/javascript">
		$( function(){
			$( "button" ).button();
			$( "#expertiseAreasButton" ).prop("disabled","disabled");
			$( "#expertiseAreasButton" ).addClass("ui-state-active");
			$( "#expertiseAreasButton" ).removeClass("ui-state-disabled");
			$( "#sendButton" ).click(function(event){
				event.preventDefault();
				$("#id_areasForm").submit();
				return false;
			});
		});
	</script>
{% endblock %}

{% block content %}
	<h1>Administraci&oacute;n</h1>
	{% include "main/admin_nav_buttons.html" %}
	<p class="verbose">
	Puede modificar las &aacute;reas de experiencia o a&ntilde;adir nuevas usando los
	espacios vac&iacute;os del final del formulario.
	</p>
	<form id="id_areasForm" class="centered" name="areasForm" method="post" action=".">
		{% csrf_token %}
		{% include "formset_tabular.html" %}
		<div id="buttonsArea">
			<button id="sendButton">Guardar</button>
		</div>
	</form>
{% endblock %}

source/mediadores/templates/main/contact.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
	{% include "jqueryui-headers.html" %}
	<link rel="stylesheet" href="/static-files/css/forms.css" />
	<link rel="stylesheet" href="/static-files/css/contact.css"/>
	{{ contactForm.media }}
	<script>
		$(function(){
			$( "button" ).button();
			{% if not sent %}
			$( "#sendButton" ).click(function(event){
				event.preventDefault();
				$("#id_contactForm").submit();
				return false;
			});
			{% else %}
			$( "input" ).prop("disabled",true).addClass("ui-state-disabled");
			$( "button" ).prop("disabled",true).addClass("ui-state-disabled");
			$( "textarea" ).prop("disabled",true).addClass("ui-state-disabled");
			{% endif %}
			{% if sent or error %}
			$("#sentDlg").dialog({
				modal: true,
				buttons:{
					Ok: function(){
						$(this).dialog("close");
					}
				}
			});
			{% endif %}
		});
	</script>
{% endblock %}

{% block nav_path %}
	{% if institution %}
		> <a class="nav_link" href="/{{ institution.id }}/">{{ institution.name }}</a> > Contacto
	{% else %}
		> Contacto
	{% endif %}
{% endblock %}

{% block content %}
	<h1>Contacto</h1>
	<p class="verbose">
	Desde aqu&iacute; puede preguntarnos cualquier duda que tenga respecto a las mediaciones o con la utilizaci&oacute;n de esta plataforma.
	</p>
	<p class="verbose">
	Estaremos encantados de atenderle.
	</p>
	{% if sent %}
	<div id="sentDlg" title="Mensaje enviado">
		<p>
			<span class="ui-icon ui-icon-circle-check" style="float: left; margin: 0 7px 50px 0;"></span>
			El mensaje se ha enviado correctamente.
		</p>
		<p>Compruebe que se ha enviado una copia al correo electr&oacute;nico que nos ha indicado (puede demorarse un tiempo antes de recibirlo).</p>
	</div>
	{% endif %}
	{% if error %}
	<div id="sentDlg" title="No se ha podido enviar">
		<p>
			<span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 50px 0;"></span>
			Ha ocurrido un error con el env&iacute;o del mensaje.
		</p>
		<p>Revise los datos que acaba de introducir. Si el problema persiste, p&oacute;ngase en contacto con nosotros.</p>
	</div>
	{% endif %}

	<form id="id_contactForm" class="centered" name="contactForm" method="post" action="."> {% csrf_token %}
		{% for hidden in contactForms.hidden_fields %}
			{{ hidden }}
		{% endfor %}
		<table>
			{{ contactForm.as_table }}
		</table>
		
		<table id="sendTable">
			<tr>				
				<td id="captcha">
					{% if not sent and not user.is_authenticated %}
						{% if captchaResponse %}
							<ul class="errorlist"><li>{{ captchaResponse }}</li></ul>
						{% endif %}
						<script type="text/javascript" src="http://api.recaptcha.net/challenge?k={{ RECAPTCHA_PUB_KEY }}">  
	            		</script> 
	            		<noscript>  
				            <iframe src="http://api.recaptcha.net/noscript?k={{ RECAPTCHA_PUB_KEY }}" height="300" width="500" frameborder="0"></iframe><br>  
					        <textarea name="recaptcha_challenge_field" rows="3" cols="40"></textarea>  
					        <input type="hidden" name="recaptcha_response_field" value="manual_challenge">  
			            </noscript>
			         {% endif %}		            
	            </td>
	            <td>
	            	<p>
						<button id="sendButton">Enviar</button>
					</p>
				</td>
			</tr>
		</table>
	</form>
{% endblock %}

source/mediadores/templates/main/degrees.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
	{% include "jqueryui-headers.html" %}
	<link rel="stylesheet" href="/static-files/css/forms.css" />
	<link rel="stylesheet" href="/static-files/css/admin_nav_buttons.css" />
	<link rel="stylesheet" href="/static-files/css/degrees.css" />
	<script type="text/javascript">
		$( function(){
			$( "button" ).button();
			$( "#degreesButton" ).prop("disabled","disabled");
			$( "#degreesButton" ).addClass("ui-state-active");
			$( "#degreesButton" ).removeClass("ui-state-disabled");
			$( "#sendButton" ).click(function(event){
				event.preventDefault();
				$("#id_degreesForm").submit();
				return false;
			});
		});
	</script>
{% endblock %}

{% block content %}
	<h1>Administraci&oacute;n</h1>
	{% include "main/admin_nav_buttons.html" %}
	<p class="verbose">
	Puede modificar las titulaciones o a&ntilde;adir nuevas usando los
	espacios vac&iacute;os del final del formulario.
	</p>
	<form id="id_degreesForm" class="centered" name="degreesForm" method="post" action=".">
		{% csrf_token %}
		{% include "formset_tabular.html" %}
		<div id="buttonsArea">
			<button id="sendButton">Guardar</button>
		</div>
	</form>
{% endblock %}

source/mediadores/templates/main/edit_mediator.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
	{% include "jqueryui-headers.html" %}
	<link rel="stylesheet" href="/static-files/css/forms.css" />
	<link rel="stylesheet" href="/static-files/css/edit_mediator.css" />
	{% block extraCSS %}{% endblock %}
	
	<script type="text/javascript" src="/static-files/js/jsi18n.js"></script>
	{{ mediatorForm.media }}
	
	<script type="text/javascript">
		function checkIsCompany(){			
			if($( "#id_isCompany" ).prop("checked")){
				$( "label[for=\"id_name\"]" ).text("Denominaci\u00f3n:");
				$( "label[for=\"id_surname\"]" ).hide();
				$( "#id_surname").hide();
			}else{
				$( "label[for=\"id_name\"]" ).text("Nombre:");
				$( "label[for=\"id_surname\"]" ).show();
				$( "#id_surname").show();
			}
		}
		$( function(){
			
			$( "#sendButton" ).button().click(function(event){
				event.preventDefault();
				$("#id_editForm").submit();
				return false;
			})
			$( "#id_insuranceExpiration" ).datepicker();
			imageCheck = document.getElementById("image-clear_id");
			if(imageCheck != null){
				imageCheck.onclick = 
					function(){
						if ($("#image-clear_id").is(":checked")){
							$(".imgWidget").hide("fade", {}, 1000, null);
						}else{
							$(".imgWidget").show("fade", {}, 1000, null);
						}
					};
			}
			$( "#id_isCompany" ).change(checkIsCompany);
			$( "#id_nif" ).on('input', function(){
				var trimmedValue = $.trim(this.value);				
				if(trimmedValue.startsWith("B") || trimmedValue.startsWith("b")){
					$( "#id_isCompany" ).prop("checked",true);
				}else{
					$( "#id_isCompany" ).prop("checked",false);
				}
				checkIsCompany();
			});
			$( "#id_nif" ).change(function(){
				this.value = $.trim(this.value).toUpperCase();
			});
			checkIsCompany();
			$( "#id_expertiseArea" ).multiselect({
				sortable: false,
				canAddNew: true,
				addNewUrl: "/ajax/add-expertise-area/",
				csrf_token: "{{ csrf_token }}",
				errorClass: "errorlist"
			});
			$( "#id_degree" ).multiselect({
				sortable: false,
				canAddNew: true,
				addNewUrl: "/ajax/add-degree/",
				csrf_token: "{{ csrf_token }}",
				errorClass: "errorlist"
			});
			{% block scriptInit %}
			{% endblock %}
		});		
	</script>	
{% endblock %}

{% block nav_path %}
	> Edici&oacute;n
{% endblock %}

{% block content %}
	<h1>Edici&oacute;n de mediador</h1>
	<form id="id_editForm" name="editForm" method="post" enctype="multipart/form-data" action=".">
		{% csrf_token %}
		
		{% for hidden in mediatorForm.hidden_fields %}
			{{ hidden }}
		{% endfor %}		
		<table>
			{{ mediatorForm.as_table }}			
		</table>
		{% block nonEditableFields %}
		{% endblock %}
		<div id="buttonArea">
			<button id="sendButton">Guardar</button>
		</div>
	</form>
	{% block afterForm %}
	{% endblock %}
{% endblock %}

source/mediadores/templates/main/home_general.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
	{% include "jqueryui-headers.html" %}
	<link rel="stylesheet" href="/static-files/css/forms.css" />
	<link rel="stylesheet" href="/static-files/css/home_general.css" />
	<script src="/static-files/js/scripts.js"></script>
	{{ searchForm.media }}
	
	
	<script type="text/javascript">
		$(function(){
			$( "button" ).button();
			$( "#sendButton" ).click( function(event){
				event.preventDefault();
				var searchForm=$("#id_searchForm");
				var fieldNames = {{ searchForm.fields.keys|safe }};
				if(formHasValues(searchForm, fieldNames)){
					searchForm.submit();
				}else{
					$( "#alertMessage" ).dialog( "open" );
					$('form:first *:input[type!=hidden]:first').focus();
				}
				return false;
			} );
			
			$( "#alertMessage" ).dialog({
				autoOpen: false,
				modal: true,
				show:{
					effect: "fade",
					duration: 500
				},
				hide:{
					effect: "fade",
					duration: 500
				},
				buttons: {
					Ok: function() {
						 $( this ).dialog( "close" );
					}
				 }
			});
			$( "select[multiple]" ).multiselect({
				sortable: false
				});
		});
	</script>
{% endblock %}

{% block nav_path %} > {{ institution.name }}{% endblock %}

{% block content %}
	<h1>B&uacute;squeda de mediador</h1>
	<p class="verbose">
		Esta es la p&aacute;gina para realizar solicitudes de mediadores de la C&aacute;mara de
		Comercio e Industria de Segovia.
	</p>
	<p class="verbose">
		Si necesita un mediador, puede buscarlo utilizando el siguiente formulario.
		Para ello introduzca al menos un campo para realizar la b&uacute;squeda.
	</p>
	<p class="verbose">Puede utilizar tantos campos como desee.</p>
	<form class="centered" id="id_searchForm" name="searchForm" method="post" action="/list/{{institution.id}}/">
		{% csrf_token %}
		{% for hidden in searchForm.hidden_fields %}
    		{{ hidden }}
		{% endfor %}
		<table id="fieldsTable">
			{{ searchForm.as_table }}
		</table>
		<div id="buttonArea">
			<button id="sendButton">Encontrar</button>
		</div>
	</form>
	<div id="alertMessage" title="Introduzca criterio de b&uacute;squeda">
		<p>
			<span class="ui-icon ui-icon-info" style="float: left; margin: 0 7px 50px 0;"></span>
			Debe rellenar como m&iacute;nimo un campo para poder realizar la b&uacute;squeda.
		</p>
		<p>
			Por favor, int&eacute;ntelo de nuevo.
		</p>
	</div>
{% endblock %}

source/mediadores/templates/main/home_mediator.html
{% extends "main/edit_mediator.html" %}
{% load i18n %}

{% block extraCSS %}
	<link rel="stylesheet" href="/static-files/css/home_mediator.css" />
{% endblock %}

{% block scriptInit %}
	$("#id_nif").prop("readonly",true).addClass("ui-state-disabled");
	$("#id_expertiseArea, #id_degree ").multiselect({sortable:false});
	{% if dataUpdated %}
	$("#updatedDlg").dialog({
		modal: true,
		buttons: {
			Ok: function(){
				$(this).dialog("close");
			}
		}
	});
	{% endif %}
{% endblock %}

{% block nav_path %}
{% endblock %}

{% block nonEditableFields %}
	<div id="nonEditableFields">
		<div id="degree">
			<table>
				<tr>
					<th>Titulaci&oacute;n</th>
					<td>
						<ul>
							{% for degree in mediator.degree.all %}
								<li>{{ degree }}</li>
							{% endfor %}
						</ul>
					</td>
				</tr>
			</table>
		</div>
		<div id="expertiseArea">
			<table>
				<tr>
					<th>&Aacute;reas de experiencia</th>
					<td>
						<ul>
							{% for area in mediator.expertiseArea.all %}
								<li>{{ area }}</li>
							{% endfor %}
						</ul>
					</td>
				</tr>
			</table>
		</div>
		<div id="insuranceData">
			<table>
				<tr><th>Entidad aseguradora:</th><td>{{ mediator.insuranceEntity.name }}</td></tr>
				<tr><th>P&oacute;liza:</th><td>{{ mediator.insuranceContract }}</td></tr>
				<tr><th>Expiraci&oacute;n de la p&oacute;liza:</th><td>{{ mediator.insuranceExpiration }}</td></tr>
			</table>
		</div>
		<p class="helptext">					 
			Para cualquier actualizaci&oacute;n o rectificaci&oacute;n de los datos de este apartado, por favor,
			 dir&iacute;jase a la entidad mediadora en la que sus datos est&aacute;n registrados.
		</p>
	</div>
{% endblock %}

{% block afterForm %}
	{% if dataUpdated %}
		<div id="updatedDlg" title="Datos guardados">
			<p>
				<span class="ui-icon ui-icon-info"></span>
				Sus datos han sido guardados en nuestro sistema.
			</p>
		</div>
	{% endif %}
{% endblock %}